version: 0.2

env:
  variables:
    DOCKERHUB_USERNAME: sudheerttech
    DOCKERHUB_PASSWORD: Riya@2026
    IMAGE_NAME: brain-tasks-app
    IMAGE_TAG: latest
    CLUSTER_NAME: brain-tasks-cluster
    AWS_REGION: us-east-1

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-01-04/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo "Checking AWS identity..."
      - aws sts get-caller-identity

      - echo "Updating kubeconfig..."
      - aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME

  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - echo Build started on `date`
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME

  build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - echo Deploying to EKS cluster...
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl set image deployment/brain-tasks-app brain-tasks-container=$DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - kubectl rollout status deployment/brain-tasks-app

  post_build:
    commands:
      - echo Build and deployment complete on `date`

artifacts:
  files: []

